using Caly.Pdf.Models;
using UglyToad.PdfPig.Content;
using UglyToad.PdfPig.Core;
using UglyToad.PdfPig.DocumentLayoutAnalysis;
using UglyToad.PdfPig.DocumentLayoutAnalysis.WordExtractor;

namespace Caly.Pdf.Layout
{
    /*
     * From PdfPig
     */

    /// <summary>
    /// Nearest Neighbour Word Extractor.
    /// This implementation leverages bounding boxes.
    /// </summary>
    public sealed class CalyNNWordExtractor
    {
        private readonly CalyNNWordExtractorOptions options;

        /// <summary>
        /// Create an instance of Nearest Neighbour Word Extractor, <see cref="CalyNNWordExtractor"/>.
        /// </summary>
        public static readonly CalyNNWordExtractor Instance = new();

        /// <summary>
        /// Create an instance of Nearest Neighbour Word Extractor using default options values.
        /// </summary>
        public CalyNNWordExtractor() : this(new CalyNNWordExtractorOptions())
        {
        }

        /// <summary>
        /// Create an instance of Nearest Neighbour Word Extractor using options values.
        /// </summary>
        /// <param name="options">The <see cref="NearestNeighbourWordExtractor.NearestNeighbourWordExtractorOptions"/> to use.</param>
        /// <exception cref="ArgumentNullException"></exception>
        public CalyNNWordExtractor(CalyNNWordExtractorOptions options)
        {
            this.options = options ?? throw new ArgumentNullException(nameof(options));
        }

        /// <summary>
        /// Get the words.
        /// </summary>
        /// <param name="letters">The page's letters to group into <see cref="Word"/>s.</param>
        /// <param name="cancellationToken"></param>
        /// <returns>The <see cref="Word"/>s generated by the nearest neighbour method.</returns>
        public IEnumerable<PdfWord> GetWords(IReadOnlyList<PdfLetter> letters, CancellationToken cancellationToken)
        {
            if (letters is null || letters.Count == 0)
            {
                return Array.Empty<PdfWord>();
            }

            var parallelOptions = new ParallelOptions()
            {
                MaxDegreeOfParallelism = options.MaxDegreeOfParallelism,
                CancellationToken = cancellationToken
            };

            if (options.GroupByOrientation)
            {
                Span<int> counts = stackalloc int[OrientationBucketsCount];
                for (int i = 0; i < letters.Count; i++)
                {
                    counts[GetOrientationBucket(letters[i].TextOrientation)]++;
                }

                // Most pages have a single orientation: no need to copy the letters.
                for (int i = 0; i < OrientationBucketsCount; i++)
                {
                    if (counts[i] == letters.Count)
                    {
                        return GetWords(letters, options.MaximumDistance, GetDistanceMeasure(i), options.FilterPivot,
                            options.Filter, parallelOptions);
                    }
                }

                var buckets = new PdfLetter[OrientationBucketsCount][];
                for (int i = 0; i < OrientationBucketsCount; i++)
                {
                    if (counts[i] > 0)
                    {
                        buckets[i] = new PdfLetter[counts[i]];
                    }
                }

                // Filled from the end, so that the letters keep their order within each bucket.
                for (int i = letters.Count - 1; i >= 0; i--)
                {
                    var letter = letters[i];
                    int bucket = GetOrientationBucket(letter.TextOrientation);
                    buckets[bucket][--counts[bucket]] = letter;
                }

                // Buckets are processed in order, so that the words order is deterministic.
                // Each bucket is already processed in parallel.
                List<PdfWord>? results = null;
                for (int i = 0; i < buckets.Length; i++)
                {
                    if (buckets[i] is null) continue;
                    var words = GetWords(buckets[i], options.MaximumDistance, GetDistanceMeasure(i), options.FilterPivot,
                        options.Filter, parallelOptions);
                    if (results is null)
                    {
                        results = words;
                    }
                    else
                    {
                        results.AddRange(words);
                    }
                }

                return results ?? [];
            }
            else
            {
                return GetWords(letters,
                    options.MaximumDistance, options.DistanceMeasure, options.FilterPivot,
                    options.Filter, parallelOptions);
            }
        }

        private const int OrientationBucketsCount = 5;
        private const int OtherOrientationBucket = 4;

        private static int GetOrientationBucket(TextOrientation orientation)
        {
            switch (orientation)
            {
                case TextOrientation.Horizontal: return 0;
                case TextOrientation.Rotate270: return 1;
                case TextOrientation.Rotate180: return 2;
                case TextOrientation.Rotate90: return 3;
                default: return OtherOrientationBucket;
            }
        }

        private Func<PdfPoint, PdfPoint, float> GetDistanceMeasure(int bucket)
        {
            return bucket == OtherOrientationBucket ? options.DistanceMeasure : options.DistanceMeasureAA;
        }

        /// <summary>
        /// Gets the words.
        /// </summary>
        /// <param name="letters">The letters in the page.</param>
        /// <param name="maxDistanceFunction">The function that determines the maximum distance between two letters (start and end base line points),
        /// e.g. Max(GlyphRectangle.Width) x 20%.
        /// <para>If the distance between the two letters is greater, a new word will be created.</para></param>
        /// <param name="distMeasure">The distance measure between two letters (start and end base line points),
        /// e.g. the Manhattan distance.</param>
		/// <param name="filterPivotFunction"></param>
        /// <param name="filterFunction">Function used to filter out connection between letters, e.g. check if the letters have the same color.
        /// <para>If the function returns false, a new word will be created.</para></param>
        /// <param name="parallelOptions">Sets the maximum number of concurrent tasks enabled.
        /// <para>A positive property value limits the number of concurrent operations to the set value.
        /// If it is -1, there is no limit on the number of concurrently running operations.</para></param>
        private static List<PdfWord> GetWords(IReadOnlyList<PdfLetter> letters,
            Func<PdfLetter, PdfLetter, float> maxDistanceFunction, Func<PdfPoint, PdfPoint, float> distMeasure,
            Func<PdfLetter, bool> filterPivotFunction,
            Func<PdfLetter, PdfLetter, bool> filterFunction, ParallelOptions parallelOptions)
        {
            if (letters is null || letters.Count == 0)
            {
                return [];
            }

            var groupedLetters = CalyClustering.NearestNeighbourGroups(letters,
                distMeasure, maxDistanceFunction,
                l => l.EndBaseLine, l => l.StartBaseLine,
                filterPivotFunction,
                filterFunction,
                parallelOptions);

            var words = new List<PdfWord>(groupedLetters.Count);
            foreach (var g in groupedLetters)
            {
                words.Add(new PdfWord(g));
            }

            return words;
        }

        /// <summary>
        /// Nearest neighbour word extractor options.
        /// </summary>
        public sealed class CalyNNWordExtractorOptions
        {
            /// <summary>
            /// <inheritdoc/>
            /// Default value is -1.
            /// </summary>
            public int MaxDegreeOfParallelism { get; init; } = -1;

            /// <summary>
            /// The maximum distance between two letters (start and end base line points) within the same word, as a function of the two letters.
            /// <para>If the distance between the two letters is greater than this maximum, they will belong to different words.</para>
            /// <para>Default value is 20% of the Max(Width, PointSize) of both letters. If <see cref="TextOrientation"/> is Other, this distance is doubled.</para>
            /// </summary>
            public Func<PdfLetter, PdfLetter, float> MaximumDistance { get; init; } = (l1, l2) =>
            {
                float maxDist = MathF.Max(MathF.Max(MathF.Max(
                    MathF.Abs((float)l1.BoundingBox.Width),
                    MathF.Abs((float)l2.BoundingBox.Width)),
                    l1.PointSize), l2.PointSize) * 0.2f;

                if (l1.TextOrientation == TextOrientation.Other || l2.TextOrientation == TextOrientation.Other)
                {
                    return 2.0f * maxDist;
                }
                return maxDist;
            };

            /// <summary>
            /// The default distance measure used between two letters (start and end base line points).
            /// <para>Default value is the Euclidean distance.</para>
            /// </summary>
            public Func<PdfPoint, PdfPoint, float> DistanceMeasure { get; init; } = CalyDistances.Euclidean;

            /// <summary>
            /// The distance measure used between two letters (start and end base line points) with axis aligned <see cref="TextOrientation"/>.
            /// <para>Only used if <see cref="GroupByOrientation"/> is set to <c>true</c>.</para>
            /// <para>Default value is the Manhattan distance.</para>
            /// </summary>
            public Func<PdfPoint, PdfPoint, float> DistanceMeasureAA { get; init; } = CalyDistances.Manhattan;

            /// <summary>
            /// Function used to filter out connection between letters, e.g. check if the letters have the same color.
            /// If the function returns <c>false</c>, letters will belong to different words.
            /// <para>Default value checks whether the neighbour is a white space or not. If it is the case, it returns <c>false</c>.</para>
            /// </summary>
            public Func<PdfLetter, PdfLetter, bool> Filter { get; init; } = (_, l2) =>
            {
                var spanL2 = l2.Value.AsSpan();
                return !spanL2.IsWhiteSpace() && !spanL2.IsPunctuation() && !spanL2.IsSeparator();
            };

            /// <summary>
            /// Function used prior searching for the nearest neighbour. If return false, no search will be done.
            /// <para>Default value checks whether the current letter is a white space or not. If it is the case, it returns false and no search is done.</para>
            /// </summary>
            public Func<PdfLetter, bool> FilterPivot { get; init; } = l =>
            {
                var spanL = l.Value.AsSpan();
                return !spanL.IsWhiteSpace() && !spanL.IsPunctuation() && !spanL.IsSeparator();
            };

            /// <summary>
            /// If <c>true</c>, letters will be grouped by <see cref="TextOrientation"/> before processing.
            /// The <see cref="DistanceMeasureAA"/> will be used on axis aligned letters, and the <see cref="DistanceMeasure"/> on others.
            /// <para>If <c>false</c>, <see cref="DistanceMeasure"/> will be used for all letters, and <see cref="DistanceMeasureAA"/> won't be used.</para>
            /// <para>Default value is true.</para>
            /// </summary>
            public bool GroupByOrientation { get; init; } = true;
        }
    }
}
