name: Windows arm64

on:
  push:
    branches: [master, develop]
  pull_request:
    branches: [master, develop]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  tests:
    uses: ./.github/workflows/tests.yml
    with:
      runs-on: windows-11-arm
      target: windows-arm64
